
export interface IEmployeeForm {
	id:number,
	Name: string,
	Email: string,
	Code: string,
	Address: string,
	state_Id:number,
	Region_Id: number,
	Image: string,
	BirthDate: string,
	Mobile: string,
	NId: string,
	MilitaryStatus_Id: number,
	MartialStatus_Id: number,
	University: string,
	Qualification: string,
	GraduateDate: string,
	Department_Id:number,
	Section_Id:number,
	JobSection_Id: number,
	HireDate: string,
	Branch_Id: number,
	IsTechnician: boolean
}